--
-- PostgreSQL database dump
--

\restrict q0kM6MswVQt16fjhgy5SmbhdJnzdC6qHHUptaJ4iuXb4meAEHesbrvAmtZ2Ahnn

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment (
    id integer NOT NULL,
    player_id integer,
    game_id integer,
    text character varying(500),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


ALTER TABLE public.comment OWNER TO postgres;

--
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game (
    id integer NOT NULL,
    date date,
    "time" time without time zone,
    status character varying(255),
    created date,
    updated date,
    place_id integer
);


ALTER TABLE public.game OWNER TO postgres;

--
-- Name: game_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.place (
    id integer NOT NULL,
    address character varying(100) NOT NULL,
    administrator_phone_number character varying(30),
    created date,
    name character varying(20) NOT NULL,
    updated date
);


ALTER TABLE public.place OWNER TO postgres;

--
-- Name: place_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.player (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    surname character varying(30) NOT NULL,
    age integer,
    city character varying(255),
    created date,
    updated date,
    role character varying(255),
    password character varying(255),
    enabled boolean,
    CONSTRAINT player_age_check CHECK ((age > 3))
);


ALTER TABLE public.player OWNER TO postgres;

--
-- Name: player_2_game; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.player_2_game (
    player_id integer NOT NULL,
    game_id integer NOT NULL
);


ALTER TABLE public.player_2_game OWNER TO postgres;

--
-- Name: player_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: comment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comment (id, player_id, game_id, text, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: game; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.game (id, date, "time", status, created, updated, place_id) FROM stdin;
64	2026-09-16	19:30:00	Passed	2026-09-17	2026-09-18	2
29	2026-06-03	19:30:00	Passed	2026-08-20	2026-09-18	1
33	2026-07-01	19:30:00	Passed	2026-08-20	2026-09-18	1
32	2026-06-24	19:30:00	Passed	2026-08-20	2026-09-18	1
35	2026-07-22	19:30:00	Passed	2026-08-20	2026-09-18	1
34	2026-07-15	19:30:00	Passed	2026-08-20	2026-09-18	1
37	2026-08-05	19:30:00	Passed	2026-08-20	2026-09-18	1
36	2026-07-29	19:30:00	Passed	2026-08-20	2026-09-18	1
39	2026-08-19	19:30:00	Passed	2026-08-20	2026-09-18	1
38	2026-08-12	19:30:00	Passed	2026-08-20	2026-09-18	1
31	2026-06-17	19:30:00	Passed	2026-08-20	2026-09-18	1
30	2026-06-10	19:30:00	Passed	2026-08-20	2026-09-18	1
61	2026-08-26	19:30:00	Passed	2026-08-25	2026-09-18	1
63	2026-09-09	19:30:00	Passed	2026-09-10	2026-09-18	1
62	2026-09-02	19:30:00	Passed	2026-09-02	2026-09-18	1
74	2026-09-23	19:30:00	Passed	2026-09-18	2026-09-24	2
\.


--
-- Data for Name: place; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.place (id, address, administrator_phone_number, created, name, updated) FROM stdin;
1	Гродно, ул. Коммунальная, 3	+375295490491	2026-09-18	Красное знамя	2026-09-18
2	Гродно, ул. Суворова, 254	+375295879314	2026-09-18	Суворова 254	2026-09-18
\.


--
-- Data for Name: player; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.player (id, name, surname, age, city, created, updated, role, password, enabled) FROM stdin;
57	Андрей	Запольский	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
59	Максим	Роман	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
61	Вадим	Шлык	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
62	Валера	Смольский	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
63	Влад	Ольховик	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
64	Дима	Пекша	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
66	Евгений	Гайданович	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
67	Иван	Карпало	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
68	Игорь	Бубейко	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
69	Максим	Шеляг	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
70	Павел	Бородич	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
71	Паша	Банцевич	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
72	Роман	Санюк	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
74	Сергей	Мисюкевич	32	Гродно	2026-08-20	2026-08-20	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
60	Евгений	Кудзеля	32	Гродно	2026-08-20	2026-09-02	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
65	Дмитрий	Толкачёв	32	Гродно	2026-08-20	2026-09-02	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
83	Денис	Шеляг	32	Гродно	2026-09-06	2026-09-10	USER	$2a$12$ZthRbx/wfp2CxZWlxS0aZ.Alm5QUBBs77/ElBmLGXLIY8N23v2qEC	t
56	Сергей	Дудко	32	Гродно	2026-08-17	2026-08-17	USER	$2a$12$d0lagd0nOoCaz.7GA91UNeJdm2jfavOQBaV9NR4nA.G/kFE8sJwkS	t
51	Евгений	Ковалевский	32	Гродно	2026-08-17	2026-08-17	ADMIN	$2a$12$0OoMm2b8nbuAXALHPWkjwO9P1px9fMbr9bOKXQ2/wRfMpgAnzoeyS	t
73	Саша	Амброжевич	32	Гродно	2026-08-20	2026-09-24	USER	$2a$12$yVe7JAVE0wsmKQRkDVcjp.V2TOzcE2Uw9zUNSl1plgFl52aZU4fq2	t
\.


--
-- Data for Name: player_2_game; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.player_2_game (player_id, game_id) FROM stdin;
72	29
70	29
69	29
56	29
63	29
59	29
71	29
64	29
51	29
51	30
56	30
63	30
64	30
72	30
59	30
65	30
66	30
69	30
51	31
74	31
72	31
71	31
66	31
56	31
62	31
67	31
64	31
65	31
69	31
51	32
74	32
66	32
56	32
72	32
67	32
64	32
63	32
60	32
71	32
69	32
51	33
63	33
60	33
71	33
67	33
72	33
69	33
56	33
68	33
51	34
68	34
60	34
67	34
71	34
56	34
59	34
64	34
63	34
66	34
65	34
69	34
70	34
51	35
68	35
63	35
71	35
64	35
56	35
74	35
60	35
59	35
69	35
66	35
51	36
64	36
72	36
60	36
59	36
70	36
63	36
71	36
66	36
51	37
70	37
68	37
71	37
63	37
60	37
65	37
72	37
69	37
59	37
66	37
51	38
64	38
56	38
71	38
63	38
65	38
74	38
67	38
69	38
59	38
61	38
72	38
66	38
60	38
56	39
61	39
63	39
71	39
59	39
64	39
60	39
69	39
72	39
74	39
51	39
51	61
64	61
68	61
60	61
69	61
74	61
61	61
72	61
62	61
59	61
67	61
63	61
56	61
71	61
51	62
71	62
68	62
60	62
74	62
59	62
65	62
72	62
63	62
69	62
61	62
64	62
56	62
67	62
57	62
62	62
51	63
71	63
56	63
57	63
67	63
60	63
63	63
64	63
59	63
62	63
65	63
59	64
71	64
63	64
70	64
61	64
60	64
56	64
68	64
64	64
83	64
69	64
51	64
51	74
83	74
59	74
67	74
60	74
70	74
63	74
71	74
56	74
57	74
69	74
73	36
73	38
73	33
73	35
73	31
73	63
73	39
73	30
73	37
73	34
73	64
73	74
73	61
73	29
\.


--
-- Name: comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comment_id_seq', 67, true);


--
-- Name: game_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.game_id_seq', 78, true);


--
-- Name: place_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.place_id_seq', 9, true);


--
-- Name: player_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.player_id_seq', 84, true);


--
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- Name: game game_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_pkey PRIMARY KEY (id);


--
-- Name: place place_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT place_pkey PRIMARY KEY (id);


--
-- Name: player_2_game player_2_game_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_2_game
    ADD CONSTRAINT player_2_game_pkey PRIMARY KEY (player_id, game_id);


--
-- Name: player player_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);


--
-- Name: comment comment_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.game(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: comment comment_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: game fkoh7jrrfy7e7uwtugcqvsmv7qy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT fkoh7jrrfy7e7uwtugcqvsmv7qy FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- Name: player_2_game player_2_game_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_2_game
    ADD CONSTRAINT player_2_game_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.game(id);


--
-- Name: player_2_game player_2_game_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_2_game
    ADD CONSTRAINT player_2_game_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player(id);


--
-- PostgreSQL database dump complete
--

\unrestrict q0kM6MswVQt16fjhgy5SmbhdJnzdC6qHHUptaJ4iuXb4meAEHesbrvAmtZ2Ahnn

